#!/usr/bin/env bash
set -e

show_help() {
  echo >&2 "podman-desktop
    --name <name>             virtual machine name
    --identity <path/to/key>  user ssh key
    --mount                   mount docker-desktop mounts
    <version>                 version of ubuntu (see multipass fetch)
  "
}
die() { echo >&2 "$@"; exit -1 }
command -v multipass 2>&1 >/dev/null || die "missing multipass"
command -v podman 2>&1 >/dev/null || die "missing podman"

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      show_help
      exit
      ;;
    -n|--name)
      INSTANCE_NAME="$2"
      shift; shift
      ;;
    -i|--identity)
      IDENTITY="$2"
      shift; shift
      ;;
    -m|--mount)
      MOUNT="YES"
      shift
      ;;
    *) # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL[@]}"


INSTANCE_NAME="${INSANCE_NAME:-podman}"
IDENTITY="${IDENTITY:-~/.ssh/id_rsa}"
PUBKEYFILE=${IDENTITY}.pub
VERSION_ID="${POSITIONAL[0]:-20.04}"
MOUNTS=${MOUNTS:-/Users /Volumes /private /tmp /var/folders} # Docker Desktop Defaults

test -f $IDENTITY || die "cannot find identity $IDENTITY"
test -f $PUBKEYFILE || die "cannot find pubkey $PUBKEYFILE"
PUBKEY=$(cat ${PUBKEYFILE})

multipass set client.primary-name=$INSTANCE_NAME

echo >&2 "this may take a while - to view progress:

    multipass exec podman -- tail -f /var/log/cloud-init-output.log
"

echo "
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ${PUBKEY}

apt:
  preserve_sources_list: true
  sources:
    libcontainers.list:
      source: \"deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /\"
      keyid: 4D64390375060AA4

package_upgrade: true
packages:
  - podman
  - containerd
  - fuse-overlayfs
" | multipass launch \
    --cpus 2 \
    --mem 2G \
    --disk 10G \
    --name ${INSTANCE_NAME} \
    --cloud-init - \
    ${VERSION_ID}

multipass exec $INSTANCE_NAME -- systemctl --user enable --now podman.socket
multipass exec $INSTANCE_NAME -- sudo loginctl enable-linger ubuntu
multipass exec $INSTANCE_NAME -- sudo systemctl enable --now ssh.service

IP=$(multipass info ${INSTANCE_NAME} | grep IPv4: | cut -d ':' -f2 | tr -ds ' ' '')

podman system connection add $INSTANCE_NAME --identity "${IDENTITY}" ssh://ubuntu@"${IP}"/run/user/1000/podman/podman.sock

[[ "$MOUNT" = "yes" ]] && for mount in $MOUNTS; do multipass mount "$mount" $INSTANCE_NAME; done

echo "${INSTANCE_NAME} created\n"

echo >&2 "You may want to add the following to your ~/.ssh/config:

    Host ${IP}
      ForwardAgent yes
      User ubuntu
"

echo >&2 "To remove:

    podman system connection remove \"$INSTANCE_NAME\"
    multipass stop \"$INSTANCE_NAME\"
    multipass delete \"$INSTANCE_NAME\"
    multipass purge
"
